name: Main

on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'Spotify ID of song'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install spotdl
        run: sudo pip3 install spotdl

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Install dependencies
        run: pip3 install -U spotipy

      - name: Install dependencies
        run: sudo apt install ffmpeg python3-pyqt5 imagemagick xvfb libxcb-xinerama0

      - name: Clone Audio Visualizer Python repo
        run: git clone https://github.com/djfun/audio-visualizer-python

      - name: Install Audio Visualizer Python
        run: pip3 install audio-visualizer-python/

      - name: Download song
        run: spotdl --output {track-id} --format mp3 --download ${{ github.event.inputs.id }}

      - name: Generate visualizer
        run: xvfb-run avp -c 0 classic layout=top color=255,255,255 -i ${{ github.event.inputs.id }}.mp3 -o ${{ github.event.inputs.id }}.mp4 --no-preview

      - name: Run main
        run: python3 main.py ${{ github.event.inputs.id }}

      - name: Zip files
        uses: papeloto/action-zip@v1
        with:
          files: songs/${{ github.event.inputs.id }}
          dest: data.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.id }}
          body: Output for ${{ github.event.inputs.id }}.
          files: songs/${{ github.event.inputs.id }}/output.mp4, data.zip